### ISSUE TITLE
Countdown to sprints

### ISSUE THREAD

**Issue by gorgoneye** [Omlahid/NaNoWriMo-Discord-Bot#5]
Not so much an issue, but if you are able, it would be nice to have an update where you can set a countdown time, so the sprint doesn't start immediately when the command does. I tried implementing this myself, but unfortunately, I lack the skill. Thanks!

**Comment by Omlahid** [comment]
Thank you for the suggestion! It is definitely something that I had planned to do! I'll let you know when it's implemented, but it should be there before the next NaNoWriMo :)

If you need help implementing the bot let me know. I'd be glad to help :)

**Comment by Omlahid** [comment]
After talking to my current users, I've decided to add a default 15 second waiting time between calling the !sprint command and the actual start of the sprint.

I hope this helps you! If you would want the waiting time to be configurable, just let me know.

If you wish to change it yourself, you'll find it in the startSprintDelay() function of the bot.js file. Change the 15000 number to whichever amount of time (in milliseconds) you wish.

I'll consider this issue fixed in the meantime.
